config/routes.rb
Rails.application.routes.draw do

 #devise_for :customers, controllers: {
 #  registrations: "public/registrations",
 # sessions: 'public/sessions'
 # }

 devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

 devise_for :admin,
    skip: [:registrations, :passwords] ,
    controllers: {sessions: "admin/sessions"}

  get '/search', to: 'searchs#search'

# public側ルーティング
  scope module: :public do
    root to: 'homes#top'
    get '/about', to: 'homes#about'
    get '/customers/quit', to: 'customers#quit'
    patch '/customers/out', to: 'customers#out'
    get '/orders/thanx', to: 'orders#thanx'
    post '/orders/confirm', to: 'orders#confirm'
    resources :items, only: [:show, :index]
    resources :orders, only: [:show, :new, :index, :create]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :customers, only: [:show, :update, :edit]
    get '/customers/information', to: 'customers#show'
    get '/customers/information/edit', to: 'customers#edit'
    patch '/customers/information', to: 'customers#update'
    #resources :sessions, only: [:new, :create, :destroy]
    delete '/cart_items/all_destroy', to: 'cart_items#all_destroy'
    resources :cart_items, only: [:index, :create, :update, :destroy]
  end


# admin側ルーティング
  namespace :admin do
    get '' => 'homes#top'
    resources :items, only: [:new, :create, :show, :index, :update, :edit]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:edit, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:show, :index, :update, :edit]
    #resources :sessions, only: [:new, :create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :cart_item, dependent: :destroy
  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :price, presence: true
  def with_tax_price
    (price * 1.1).floor
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
   before_action :authenticate_admin!

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:item_create] = "商品を追加しました"
      redirect_to admin_item_path(@item)
    else
      redirect_back fallback_location: root_path
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path
      flash[:notice_update] = "商品情報を更新しました"
    else
      redirect_back fallback_location: root_path
    end
  end

  private
  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :image, :price, :is_stated)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<% if @item.errors.any? %>
  <%= @item.errors.count %>件の未入力項目があります
<% end %>
<div class='container'>
  <div class="p-3 mb-2 col-md-2 font-weight-bold bg-light text-dark">商品編集</div><br>

  <%= form_with model: @item, url:admin_item_path(@item.id), method: :patch do |f| %>
    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :商品画像 %></div>
        <div class="col-lg-3"><%= f.file_field :image, accept: "image/*" %></div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :商品名 %></div>
        <div class="col-lg-4"><%= f.text_field :name, class: 'form-control item_name' %></div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :商品説明 %></div>
        <div class="col-lg-4"><%= f.text_area :introduction, class: 'form-control item_introduction' %></div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :ジャンル %></div>
        <div class="col-lg-3"><%= f.collection_select :genre_id, Genre.all ,:id, :name, include_blank: "--選択してください--" %></div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :税抜価格 %></div>
        <div class="col-lg-1"><%= f.text_field :price, class: 'form-control item_price' %></div>
        円
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :販売ステータス %></div>
        <div class="col-lg-1"><%= f.radio_button :is_stated, true %><%= f.label :販売中 %></div>
        <div class="col-lg-2"><%= f.radio_button :is_stated, false %><%= f.label :販売停止中 %></div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-2"><%= f.submit '変更を保存', class: 'btn btn-success' %></div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/items/index.html.erb
<div class='container'>
  <div class='row'>
    <div class="p-3 mb-2 bg-light text-dark">商品一覧</div>
    <div class="text-right">
      <%= link_to "＋" ,new_admin_item_path, class: 'btn btn-success' %>
  　</div>
    <table class='table'>
      <thead>
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td><%= link_to item.name ,admin_item_path(item) %></td>
            <td><%= item.price.to_s(:delimited) %></td>
            <td><%= item.genre.name %></td>
            <td><% if item.is_stated == true %>
              <strong class="text-success">販売中</strong>
            <% else %>
              <strong class="text-secondary">販売停止中</strong>
            <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/items/new.html.erb
<% if @item.errors.any? %>
  <%= @item.errors.count %>件の未入力項目があります
<% end %>
<div class='container'>
  <div class="p-3 mb-2 col-md-2 font-weight-bold bg-light text-dark">商品新規登録</div><br>

  <%= form_with model: @item, url:admin_items_path do |f| %>
    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :商品画像 %></div>
        <div class="col-lg-3"><%= f.file_field :image, accept: "image/*" %></div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :商品名 %></div>
        <div class="col-lg-4"><%= f.text_field :name, class: 'form-control item_name' %></div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :商品説明 %></div>
        <div class="col-lg-4"><%= f.text_area :introduction, class: 'form-control item_introduction' %></div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :ジャンル %></div>
        <div class="col-lg-3"><%= f.collection_select :genre_id, Genre.all ,:id, :name, include_blank: "--選択してください--" %></div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :税抜価格 %></div>
        <div class="col-lg-1"><%= f.text_field :price, class: 'form-control item_price' %></div>
        円
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :販売ステータス %></div>
        <div class="col-lg-1"><%= f.radio_button :is_stated, true %><%= f.label :販売中 %></div>
        <div class="col-lg-2"><%= f.radio_button :is_stated, false  %><%= f.label :販売停止中 %></div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-2"><%= f.submit '新規登録', class: 'btn btn-success' %></div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/items/show.html.erb
<div>
  <%= flash[:notice_update] %>
  <%= flash[:item_create] %>
</div>
<div class='container'>
  <div class="p-3 mb-2 col-md-2 font-weight-bold bg-light text-dark">商品詳細</div><br>
  <div class='row'>
    <div class="col-4">
      <%= image_tag @item.image, size: "300x300" %>
    </div>
    <div class="col-8">
      <div class="row">
  　　    <div class="col-12">
          <table class="table">
            <tbody>
              <tr>
                <td>商品名</td>
                <td><%= @item.name %></td>
              </tr>
              <tr>
                <td>商品説明</td>
                <td><%= @item.introduction %></td>
              </tr>
              <tr>
                <td>ジャンル</td>
                <td><%= @item.genre.name %></td>
              </tr>
              <tr>
                <td>税込価格(税抜価格)</td>
                <td><%= (@item.price*1.1).floor.to_s(:delimited) %>
                  (<%= @item.price.floor.to_s(:delimited) %>)円</td>
              </tr>
              <tr>
                <td>販売ステータス</td>
                <td>
                  <% if @item.is_stated == true %>
                    <strong class="text-success">販売中</strong>
                  <% else %>
                    <strong class="text-secondary">販売停止中</strong>
                  <% end %>
                </td>
              </tr>
            </tbody>
          </table>
          <%= link_to "編集する",edit_admin_item_path(@item), class: 'btn btn-success' %>
        </div>
      </div>
    </div>
  </div>
</div>