config/routes.rb
Rails.application.routes.draw do

 #devise_for :customers, controllers: {
 #  registrations: "public/registrations",
 # sessions: 'public/sessions'
 # }

 devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

 devise_for :admin,
    skip: [:registrations, :passwords] ,
    controllers: {sessions: "admin/sessions"}

  get '/search', to: 'searchs#search'

# public側ルーティング
  scope module: :public do
    root to: 'homes#top'
    get '/about', to: 'homes#about'
    get '/customers/quit', to: 'customers#quit'
    patch '/customers/out', to: 'customers#out'
    get '/orders/thanx', to: 'orders#thanx'
    post '/orders/confirm', to: 'orders#confirm'
    resources :items, only: [:show, :index]
    resources :orders, only: [:show, :new, :index, :create]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :customers, only: [:show, :update, :edit]
    get '/customers/information', to: 'customers#show'
    get '/customers/information/edit', to: 'customers#edit'
    patch '/customers/information', to: 'customers#update'
    #resources :sessions, only: [:new, :create, :destroy]
    delete '/cart_items/all_destroy', to: 'cart_items#all_destroy'
    resources :cart_items, only: [:index, :create, :update, :destroy]
  end


# admin側ルーティング
  namespace :admin do
    get '' => 'homes#top'
    resources :items, only: [:new, :create, :show, :index, :update, :edit]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:edit, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:show, :index, :update, :edit]
    #resources :sessions, only: [:new, :create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
# Include default devise modules. Others available are:
# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
# validates :name, :login, :email, presence: true
  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :phone_number, presence: true
  
  def create
    super && (is_deleted == false)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

   before_action :authenticate_admin!

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
     @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path
    else
      render 'edit'
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :phone_number, :email, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="p-3 mb-4 col-md-4 font-weight-bold bg-light text-dark"><%= @customer.last_name %>さんの会員情報編集</div>
  <%= form_with model: @customer, url: admin_customer_path do |f| %>
  <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :last_name, "会員ID" %></div>
        <div class="col-lg-3"><%= @customer.id %></div>
        <div class="col-lg-3"></div>
      </div>
    </div>
  
    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :last_name, "氏名" %></div>
        <div class="col-lg-3"><%= f.text_field :last_name, autofocus: true, class: "form-control border-dark" %></div>
        <div class="col-lg-3"><%= f.text_field :first_name, class: "form-control border-dark" %></div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :last_name_kana, "フリガナ" %></div>
        <div class="col-lg-3"><%= f.text_field :last_name_kana, autofocus: true, class: "form-control border-dark" %></div>
        <div class="col-lg-3"><%= f.text_field :first_name_kana, class: "form-control border-dark" %></div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :post_code, "郵便番号" %></div>
        <div class="col-lg-3"><%= f.text_field :post_code, class: "form-control border-dark" %></div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :address, "住所" %></div>
        <div class="col-lg-6"><%= f.text_field :address, class: "form-control border-dark" %></div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :phone_number, "電話番号" %></div>
        <div class="col-lg-3"><%= f.text_field :phone_number, class: "form-control border-dark" %></div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :email, "メールアドレス" %></div>
        <div class="col-lg-3"><%= f.email_field :email, autocomplete: "email", class: "form-control border-dark" %></div>
      </div>
    </div>
    
    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :is_deleted, "会員ステータス" %></div>
        <div class="col-lg-3">
          <%= f.radio_button :is_deleted, false %><%= f.label :有効 %>
          <%= f.radio_button :is_deleted, true %><%= f.label :退会 %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"></div>
        <div class="btn-toolbar">
          <div class="btn-group">
            <%= f.submit "変更を保存", class: 'btn btn-success', style: 'width:300px' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class='container'>
  <div class='row'>
    <div class="p-3 mb-2 bg-light text-dark">会員一覧</div>
    <table class='table'>
      <thead>
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td><%= link_to customer.last_name + " " + customer.first_name,admin_customer_path(customer) %></td>
            <td><%= customer.email %></td>
            <td><% if customer.is_deleted == false %>
              <strong class="text-success">有効</strong>
            <% else %>
              <strong class="text-secondary">無効</strong>
            <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
    <%= form_with model: @customer, url: admin_customer_path do |f| %>
    <div class="p-3 mb-4 col-md-4 font-weight-bold bg-light text-dark"><%= @customer.last_name+ " " + @customer.first_name %>さんの会員詳細</div>
    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :last_name, "会員ID" %></div>
        <div class="col-lg-3"><%= @customer.id %></div>
        <div class="col-lg-3"></div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :last_name, "氏名" %></div>
        <div class="col-lg-3"><%= @customer.last_name+ " " + @customer.first_name %></div>
        <div class="col-lg-3"></div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :last_name_kana, "フリガナ" %></div>
        <div class="col-lg-3"><%= @customer.last_name_kana+ " " + @customer.first_name_kana %></div>
        <div class="col-lg-3"></div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :post_code, "郵便番号" %></div>
        <div class="col-lg-3"><%= @customer.post_code %></div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :address, "住所" %></div>
        <div class="col-lg-6"><%= @customer.address %></div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :phone_number, "電話番号" %></div>
        <div class="col-lg-3"><%= @customer.phone_number %></div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :email, "メールアドレス" %></div>
        <div class="col-lg-3"><%= @customer.email %></div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"><%= f.label :email, "会員ステータス" %></div>
        <div class="col-lg-3">
         <% if @customer.is_deleted == false %>
           <strong class="text-success">有効</strong>
         <% else %>
           <strong class="text-secondary">無効</strong>
         <% end %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-lg-3"></div>
        <div class="btn-toolbar">
          <div class="btn-group">
            <%= link_to "編集する", edit_admin_customer_path, class: 'btn btn-success', style: 'width:100px' %>
            <%= link_to "注文履歴一覧を見る", admin_path, class: 'btn ml-5 btn-primary' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>