config/routes.rb
Rails.application.routes.draw do

 #devise_for :customers, controllers: {
 #  registrations: "public/registrations",
 # sessions: 'public/sessions'
 # }

 devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

 devise_for :admin,
    skip: [:registrations, :passwords] ,
    controllers: {sessions: "admin/sessions"}

  get '/search', to: 'searchs#search'

# public側ルーティング
  scope module: :public do
    root to: 'homes#top'
    get '/about', to: 'homes#about'
    get '/customers/quit', to: 'customers#quit'
    patch '/customers/out', to: 'customers#out'
    get '/orders/thanx', to: 'orders#thanx'
    post '/orders/confirm', to: 'orders#confirm'
    resources :items, only: [:show, :index]
    resources :orders, only: [:show, :new, :index, :create]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :customers, only: [:show, :update, :edit]
    get '/customers/information', to: 'customers#show'
    get '/customers/information/edit', to: 'customers#edit'
    patch '/customers/information', to: 'customers#update'
    #resources :sessions, only: [:new, :create, :destroy]
    delete '/cart_items/all_destroy', to: 'cart_items#all_destroy'
    resources :cart_items, only: [:index, :create, :update, :destroy]
  end


# admin側ルーティング
  namespace :admin do
    get '' => 'homes#top'
    resources :items, only: [:new, :create, :show, :index, :update, :edit]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:edit, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:show, :index, :update, :edit]
    #resources :sessions, only: [:new, :create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
	has_many   :order_details, dependent: :destroy
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { a: 0, b: 1, c: 2, d: 3, e: 4 }
  after_update do
    if self.status == 'b'#"入金確認"
      self.order_details.each {|order_detail|
      order_detail.update(status: 'b')#"製作待ち")
      }
    end
  end

  def subtotal
    item.add_tax_price * amount
  end

end


# enum status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }
#status　→　注文ステータス

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
   before_action :authenticate_admin!

  def index
    @orders = Order.all
    @order = Order.new
  end

  def show
    @item = Item.find(params[:item_id])
    @order = @item.order.new
    if params[:id] == "confirm"
    redirect_to new_order_path
    else
      @order = Order.find(params[:id])
    end
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
    if @order.update(order_params)
      @order_details.update_all(status: 'a') if @order.status == 'a' #"payment_confirmation"
     redirect_to edit_admin_order_path(@order.id)
    end
  end

#   @order = Order.find(params[:id])
#   @order_details = OrderDetail.where(order_id: params[:id])
#   if @order.update(order_params)
#     @order_details.update_all(making_status: 1) if @order.status == "payment_confirmation"
#     ## ①注文ステータスが「入金確認」とき、製作ステータスを全て「製作待ち」に更新する
#   end
#   redirect_to admin_order_path(@order)
# end

  def destroy
  end

  def confirm
      @order = Order.new(order_params)
      @address = Address.find(params[:order][:address_id])
      @order.postal_code = @address.postal_code
      @order.address = @address.address
      @order.name = @address.name
    if params[:order][:select_address] == "0"
      @order.postal_code = current_end_user.postal_code
      @order.address = current_end_user.address
      @order.name = current_end_user.first_name + current_end_user.last_name
    elsif params[:order][:select_address] == "1"
       @address = Address.find(params[:order][:address_id])
       @order.postal_code = @address.postal_code
       @order.address = @address.address
       @order.name = @address.name
    elsif params[:order][:select_address] == "2"
      @order.end_user_id = current_end_user.id
    end
      @cart_items = current_end_user.cart_items
      @order_new = Order.new
      render :confirm
  end

  private

  def order_params
  params.require(:order).permit(:payment_method, :postal_code, :address, :name, :status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/edit.html.erb
<div class='container'>
  <div class="p-3 mb-4 col-md-4 font-weight-bold bg-light text-dark">注文履歴詳細</div>
    <div class="form-group">
      <div class="row">
        <div class="col-lg-3">購入者</div>
        <div class="col-lg-3"><%= link_to admin_customer_path(@order.customer) do %>
          <%= @order.customer.last_name %>　<%= @order.customer.first_name %><% end %></div>
        <div class="col-lg-3"></div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-lg-3">配送先</div>
        <div class="col-lg-3"><%= @order.address %></div>
        <div class="col-lg-3"></div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-lg-3">注文日</div>
        <div class="col-lg-3"><%= @order.created_at.strftime("%Y-%m-%d %H:%M:%S") %></div>
        <div class="col-lg-3"></div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-lg-3">支払方法</div>
        <div class="col-lg-3"><%= @order.payment_method_i18n %></div>
        <div class="col-lg-3"></div>
      </div>
    </div>
     <div class="form-group">
      <div class="row">
        <div class="col-lg-3">注文ステータス</div>
        <div class="col-lg-3"><%= form_with(model: @order, url: admin_order_path, local: true, class: "form-row") do |f| %>
          <%= f.select :status, Order.statuses_i18n.invert, {prompt: false}, class:"form-control form-control-sm col-6"  %>
           <%= f.submit "更新", class: "btn btn-success" %>
        <% end %>
        </div>
        <div class="col-lg-3"></div>
      </div>
    </div>
  <div class="row">
    <div class="col-lg-9">
      <table class="table">
        <thead>
          <tr>
            <th class="table-active">商品名</th>
            <th class="table-active">単価（税込）</th>
            <th class="table-active">数量</th>
            <th class="table-active">小計</th>
            <th class="table-active">製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_details.each do |order_detail| %>
            <tr>
              <td><%= order_detail.item.name %></td>
              <td><%= (order_detail.price_tax * 1.1).floor.to_s(:delimited, delimiter: ',') %></td>
              <td><%= order_detail.amount %></td>
              <td><%= (order_detail.price_tax * order_detail.amount * 1.1).floor.to_s(:delimited, delimiter: ',') %></td>
              <td>
                <%= form_with(model: order_detail, url: admin_order_detail_path(order_detail), local: true, class: "form-row") do |f| %>
                <%= f.select :status, OrderDetail.statuses_i18n.invert, {prompt: false}, class:"form-control form-control-sm col-6" %>
                <%= f.submit '更新',class:"btn btn-success" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-lg-3">
      <table>
        <tbody>
          <tr>
            <td><strong>商品合計</strong></td>
            <td class="ml-2"><%= (@order.billing_price - @order.postage).to_s(:delimited, delimiter: ',') %></td>
          </tr>
          <tr>
            <td><strong>送料</strong></td>
            <td class="ml-2"><%= @order.postage.to_s(:delimited, delimiter: ',') %></td>
          </tr>
          <tr>
            <td><strong>請求合計金額</strong></td>
            <td class="ml-2"><strong><%= @order.billing_price.to_s(:delimited, delimiter: ',') %></strong></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>