config/routes.rb
Rails.application.routes.draw do

 #devise_for :customers, controllers: {
 #  registrations: "public/registrations",
 # sessions: 'public/sessions'
 # }

 devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

 devise_for :admin,
    skip: [:registrations, :passwords] ,
    controllers: {sessions: "admin/sessions"}

  get '/search', to: 'searchs#search'

# public側ルーティング
  scope module: :public do
    root to: 'homes#top'
    get '/about', to: 'homes#about'
    get '/customers/quit', to: 'customers#quit'
    patch '/customers/out', to: 'customers#out'
    get '/orders/thanx', to: 'orders#thanx'
    post '/orders/confirm', to: 'orders#confirm'
    resources :items, only: [:show, :index]
    resources :orders, only: [:show, :new, :index, :create]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :customers, only: [:show, :update, :edit]
    get '/customers/information', to: 'customers#show'
    get '/customers/information/edit', to: 'customers#edit'
    patch '/customers/information', to: 'customers#update'
    #resources :sessions, only: [:new, :create, :destroy]
    delete '/cart_items/all_destroy', to: 'cart_items#all_destroy'
    resources :cart_items, only: [:index, :create, :update, :destroy]
  end


# admin側ルーティング
  namespace :admin do
    get '' => 'homes#top'
    resources :items, only: [:new, :create, :show, :index, :update, :edit]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:edit, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:show, :index, :update, :edit]
    #resources :sessions, only: [:new, :create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def address_display
  '〒' + post_code + ' ' + address + ' ' + addressed_name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
# Include default devise modules. Others available are:
# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
# validates :name, :login, :email, presence: true
  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :phone_number, presence: true
  
  def create
    super && (is_deleted == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :item, dependent: :destroy
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :cart_item, dependent: :destroy
  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :price, presence: true
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
	has_many   :order_details, dependent: :destroy
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { a: 0, b: 1, c: 2, d: 3, e: 4 }
  after_update do
    if self.status == 'b'#"入金確認"
      self.order_details.each {|order_detail|
      order_detail.update(status: 'b')#"製作待ち")
      }
    end
  end

  def subtotal
    item.add_tax_price * amount
  end

end


# enum status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }
#status　→　注文ステータス

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum status: { a: 0, b: 1, c: 2, d: 3 }

  def create
    @order = Order.new(order_params)
    @order.customer_id = current_customer.id
      order = Order.new(order_params)
    order.save
    @cart_items = current_end_user.cart_items.all

    @cart_items.each do |cart_item|
      @order_details = OrderDetail.new
      @order_details.order_id = order.id
      @order_details.item_id = cart_item.item.id
      @order_details.price = cart_item.item.price_excluding_tax
      @order_details.number = cart_item.amount
      @order_details.manufacture_status = 0
      @order_details.save!
    end
  end

  def with_tax_price
    (price * 1.1).floor
  end

  def subtotal
    item.with_tax_price * amount
  end

  after_update do
    order_details = self.order.order_details
    if order_details.any? {|order_detail| order_detail.status == "製作中"} == true # 条件分岐：製作ステータスが1つでも製作中にだったら
      self.order.update(status: "製作中") # 注文ステータスを製作中に変更する
    elsif order_details.all? {|order_detail| order_detail.status == "製作完了"} == true # 条件分岐：製作ステータスが全て製作完了だったら
    self.order.update(status: "発送準備中") # 注文ステータスを発送準備中に変更する
    end
  end
end


# enum making_status: { production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }
#making_status → 製作ステータス

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
   before_action :authenticate_admin!

  def top
    @orders = Order.all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController

  def search
    @model = params["model"]
    @content = params["content"]
    @method = params["method"]
    @records = search_for(@model, @content, @method)
  end

  private
  def search_for(model, content, method)
    if model == 'item'
      if method == 'perfect'
        User.where(name: content)
      else
        User.where('name LIKE ?', '%'+content+'%')
      end
    elsif model == 'genre'
      if method == 'perfect'
        Post.where(name: content)
      else
        Post.where('name LIKE ?', '%'+content+'%')
      end
    end
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
  # def resource_name
  # :admin
  # end

  # def resource
  #   @resource ||= Admin.new
  # end

  # def devise_mapping
  #   @devise_mapping ||= Devise.mappings[:admin]
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="p-3 mb-2 bg-danger text-white">
    <div class='container mt-5'>
  	  <div class='row'>
    	  <div class='mx-auto'>
    		  <p>CopyRight ©Infratop.inc</p>
    	  </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-danger">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Nagano Cake</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

        <%= render 'searchs/form' %>

        <% if customer_signed_in? %>
          <li class="customer-name">
            ようこそ、<%= current_customer.last_name %> さん</br>
          </li>
          <li class="ml-4">
            <%= link_to customers_information_path(current_customer),class: 'nav-link text-light' do %>
              マイページ
            <% end %>
          </li>
          <li class="ml-4">
            <%=  link_to items_path,class: 'nav-link text-light' do %>
              商品一覧
            <% end %>
          </li>
          <li class="ml-4">
            <%=  link_to cart_items_path(current_customer),class: 'nav-link text-light' do %>
              カート
            <% end %>
          </li>
          <li class="ml-4">
            <%= link_to destroy_customer_session_path, method: :delete,class: 'nav-link text-light' do %>
              ログアウト
            <% end %>
          </li>
        <% elsif admin_signed_in? %>
          <li class="ml-4">
            <%= link_to admin_items_path,class: 'nav-link text-light' do %>
              商品一覧
            <% end %>
          </li>
          <li class="ml-4">
            <%=  link_to admin_customers_path,class: 'nav-link text-light' do %>
              会員一覧
            <% end %>
          </li>
          <li class="ml-4">
            <%=  link_to admin_path,class: 'nav-link text-light' do %>
              注文履歴一覧
            <% end %>
          </li>
          <li class="ml-4">
            <%= link_to admin_genres_path,class: 'nav-link text-light' do %>
              ジャンル一覧
            <% end %>
          </li>
          <li class="ml-4">
            <%= link_to destroy_admin_session_path, method: :delete,class: 'nav-link text-light' do %>
              ログアウト
            <% end %>
          </li>
        <% else %>
          <li class="ml-4">
            <%= link_to about_path,class: 'nav-link text-light' do %>
              About
            <% end %>
          </li>
          <li class="ml-4">
            <%= link_to items_path,class: 'nav-link text-light' do %>
              商品一覧
            <% end %>
          </li>
          <li class="ml-4">
            <%= link_to new_customer_registration_path,class: 'nav-link text-light' do %>
              新規登録
            <% end %>
          </li>
          <li class="ml-4">
            <%= link_to new_customer_session_path ,class: 'nav-link text-light' do %>
              ログイン
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
      <main>
        <p id="notice"><%= notice %></p>
        <%= yield %>
      </main>
    <%= render 'layouts/footer' %>
  </body>
</html>